name: Docker Image CI

on:
  workflow_dispatch: # 手动触发

env:
  BUILD_VERSION: 4.0.2
  IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/thingsboard

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取Gitee仓库内容
        run: |
          git clone https://${{ secrets.GITEE_USERNAME }}:${{ secrets.GITEE_TOKEN }}@gitee.com/taozhang09/thingsboard.git source-code
      - name: 安装 JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: 使用 Maven 构建 jar（跳过测试）
        run: mvn clean install -DskipTests -Dlicense.skip=true
        working-directory: ./source-code
      - name: 将打好的 jar 复制为 Docker 构建使用名
        run: |
          mkdir docker-context
          cp ./source-code/application/target/thingsboard-${BUILD_VERSION}-boot.jar docker-context/
          cp ./source-code/Dockerfile docker-context/
      - name: 查看 docker-context 目录内容
        run: ls -l docker-context
      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: 登陆 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: 查看当前目录和 docker-context 内容
        run: |
          pwd
          ls -l
          ls -l docker-context
      - name: 构建并推送 Docker 镜像
        uses: docker/build-push-action@v5
        with:
          context: ./docker-context
          file: Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.BUILD_VERSION }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            BUILD_VERSION=${{ env.BUILD_VERSION }}
            MAINTAINER=${{ secrets.DOCKER_HUB_USERNAME }}
