name: Docker Image Gateway CI

on:
  workflow_dispatch: # 手动触发

env:
  BUILD_VERSION: latest
  IMAGE_NAME: ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_NAMESPACE }}/thingsboard-gateway

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: 安装 tree（可选）
        run: sudo apt-get update && sudo apt-get install tree -y

      - name: 拉取Gitee仓库内容
        run: |
          git clone --branch master https://${{ secrets.GITEE_USERNAME }}:${{ secrets.GITEE_TOKEN }}@gitee.com/taozhang09/thingsboard-gateway.git source-code

      - name: 查看克隆后的目录结构
        run: |
          ls -al source-code
          echo "---------------------"
          tree source-code || true

      - name: Set up QEMU (for cross-platform builds)
        uses: docker/setup-qemu-action@v3

      - name: 设置 Docker Build x
        uses: docker/setup-buildx-action@v3

      - name: 登录到国内镜像仓库
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
#      - name: 登陆 Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: 构建并推送 Docker 镜像
        uses: docker/build-push-action@v5
        with:
          context: ./source-code
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.BUILD_VERSION }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            BUILD_VERSION=${{ env.BUILD_VERSION }}
            MAINTAINER=${{ secrets.REGISTRY_USERNAME }}
